-- Supabase PostgreSQL Schema for WhatsApp AI Agent

-- 1. Persona Table
CREATE TABLE personas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Contact Table
CREATE TABLE contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  phone TEXT UNIQUE NOT NULL,
  persona_id BIGINT REFERENCES personas(id) ON DELETE CASCADE,
  notes TEXT,
  last_seen_at TIMESTAMPTZ,
  last_message_at TIMESTAMPTZ,
  is_blocked BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tag Table
CREATE TABLE tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- 4. Contact_Tags (Many-to-Many join table)
CREATE TABLE contact_tags (
  contact_id BIGINT REFERENCES contacts(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (contact_id, tag_id)
);

-- 5. Chat Table
CREATE TABLE chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id BIGINT REFERENCES contacts(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('INCOMING', 'OUTGOING')),
  status TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Insight Table
CREATE TABLE insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id BIGINT REFERENCES contacts(id) ON DELETE CASCADE,
  summary TEXT NOT NULL,
  message_count INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. RelationPerson Table (1-to-1 with Contact)
CREATE TABLE relation_persons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id BIGINT UNIQUE REFERENCES contacts(id) ON DELETE CASCADE,
  my_persona TEXT,
  my_dictionary TEXT,
  user_persona TEXT,
  style TEXT,
  rules TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create a trigger to automatically update 'updated_at' on relation_persons
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_relation_persons_updated_at
BEFORE UPDATE ON relation_persons
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Add Indexes for Performance
CREATE INDEX idx_contacts_phone ON contacts(phone);
CREATE INDEX idx_chats_contact_id_created_at ON chats(contact_id, created_at DESC);
CREATE INDEX idx_insights_contact_id_created_at ON insights(contact_id, created_at DESC);
